x-app-config: &app-vars
  DB_HOST: db
  DB_USER: app
  DB_PASSWORD: app
  BROKER-USER: cueio
  BROKER_PASSWORD: cueio
  JWT_SECRET: z2RhL3l1BqTDswPCcFuRWp4Gvnrl/VKSds7jOUqk6Og=

services:

  db:
    image: postgres:18.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: tanto_faz_so_pra_dev
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - ./databases.sql:/docker-entrypoint-initdb.d/databases.sql:ro
      - ./pgdata:/var/lib/postgresql/18/docker

  broker:
    image: rabbitmq:4.2.2-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq/mnesia/
    environment:
      RABBITMQ_DEFAULT_USER: cueio
      RABBITMQ_DEFAULT_PASS: cueio
      RABBITMQ_DEFAULT_VHOST: /

  clientes:
    build:
      context: .
      dockerfile: clientes/Dockerfile
    ports:
      - "8081:8081"
    environment:
      <<: *app-vars
    depends_on:
      - db

  pagamento-externo:
    build:
      context: .
      dockerfile: pagamento-externo/Dockerfile
    ports:
      - "8086:8086"
    environment:
      <<: *app-vars
    depends_on:
      - db
