x-db-config: &db-vars
  DB_HOST: db
  DB_USER: app
  DB_PASSWORD: app

x-broker-config: &broker-vars
  BROKER-USER: cueio
  BROKER_PASSWORD: cueio

x-jwt-config: &jwt-vars
  JWT_SECRET: z2RhL3l1BqTDswPCcFuRWp4Gvnrl/VKSds7jOUqk6Og=

x-clientes: &clientes-vars
  CLIENTES_HOST: clientes
  CLIENTES_PORT: 8081

x-pagamento-externo: &pagamento-externo-vars
  PAGAMENTO_EXTERNO_HOST: pagamento-externo
  PAGAMENTO_EXTERNO_PORT: 8086
  PAGAMENTO_EXTERNO_ID: pagamentoExternoId
  PAGAMENTO_EXTERNO_SECRET: pagamentoExternoSecret

x-pagamento-interno: &pagamento-interno-vars
  PAGAMENTO_INTERNO_HOST: pagamento-interno
  PAGAMENTO_INTERNO_PORT: 8087
  PAGAMENTO_INTERNO_ID: pagamentoInternoId
  PAGAMENTO_INTERNO_SECRET: pagamentoInternoSecret  

services:

  db:
    image: postgres:18.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: tanto_faz_so_pra_dev
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - ./databases.sql:/docker-entrypoint-initdb.d/databases.sql:ro
      - ./pgdata:/var/lib/postgresql/18/docker

  broker:
    image: rabbitmq:4.2.2-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq/mnesia/
    environment:
      RABBITMQ_DEFAULT_USER: cueio
      RABBITMQ_DEFAULT_PASS: cueio
      RABBITMQ_DEFAULT_VHOST: /

  clientes:
    build:
      context: .
      dockerfile: clientes/Dockerfile
    ports:
      - "8081:8081"
    environment:
      <<: [*clientes-vars, *db-vars, *jwt-vars]
    depends_on:
      - db

  pagamento-externo:
    build:
      context: .
      dockerfile: pagamento-externo/Dockerfile
    ports:
      - "8086:8086"
    environment:
      <<: [*pagamento-externo-vars, *pagamento-interno-vars]
    depends_on:
      - db
  
  pagamento-interno-web:
    build:
      context: .
      dockerfile: pagamento-interno-web/Dockerfile
    ports:
      - "8087:8087"
    environment:
      <<: [*pagamento-externo-vars, *pagamento-interno-vars, *db-vars, *jwt-vars]
    depends_on:
      - db
