server:
  port: ${PAGAMENTO_EXTERNO_PORT:8086}

spring:
  application:
    name: pagamentoexterno

  threads:
    virtual:
      enabled: true

security:
  auth-type: client-secret

# Clientes aceitos
internal-backend:
  clients:
    - client-id: ${PAGAMENTO_EXTERNO_ID:pagamentoExternoId}
      client-secret: ${PAGAMENTO_EXTERNO_SECRET:pagamentoExternoSecret}
  webhooks:
    - url: http://${PAGAMENTO_INTERNO_HOST:localhost}:${PAGAMENTO_INTERNO_PORT:8087}/webhook
      client-id: ${PAGAMENTO_INTERNO_ID:pagamentoInternoId}
      client-secret: ${PAGAMENTO_INTERNO_SECRET:pagamentoInternoSecret}