server:
  port: ${RESERVAS_EXTERNO_VOO_PORT:8083}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/externo_voo
    hikari:
      pool-name: ExternoVooPool

internal-backend:
  clients:
    - client-id: ${RESERVAS_EXTERNO_VOO_ID:reservasExternoVooId}
      client-secret: ${RESERVAS_EXTERNO_VOO_SECRET:reservasExternoVooSecret}
