server:
  port: ${SESSAO_COMPRA_WEB_PORT:8080}

spring:
  application:
    name: sessaocompra

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/sessaocompra
    username: ${DB_USER:app}
    password: ${DB_PASSWORD:app}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: SessaoCompraPool

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

    show-sql: true

  flyway:
    enabled: true
    validate-on-migrate: true

jwt:
  public-key: ${JWT_PUBLIC_KEY}

reservas-interno-hotel:
  url: http://${RESERVAS_INTERNO_WEB_HOTEL_HOST:localhost}:${RESERVAS_INTERNO_WEB_HOTEL_PORT:8084}
  client-id: ${RESERVAS_INTERNO_WEB_HOTEL_ID:reservasInternoHotelId}
  client-secret: ${RESERVAS_INTERNO_WEB_HOTEL_SECRET:reservasInternoHotelSecret}

reservas-interno-voo:
  url: http://${RESERVAS_INTERNO_WEB_VOO_HOST:localhost}:${RESERVAS_INTERNO_WEB_VOO_PORT:8085}
  client-id: ${RESERVAS_INTERNO_WEB_VOO_ID:reservasInternoVooId}
  client-secret: ${RESERVAS_INTERNO_WEB_VOO_SECRET:reservasInternoVooSecret}
