server:
  port: ${CLIENTES_PORT:8081}

spring:
  application:
    name: clientes
  
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/clientes
    username: ${DB_USER:app}
    password: ${DB_PASSWORD:app}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: ClientesPool

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

    show-sql: true

  flyway:
    enabled: true
    validate-on-migrate: true

jwt:
  private-key: ${JWT_PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNV5Ldmbb5lpgaYkEM/UI4vImjrgQVjuYTpFHIVlvIluoHV9vHl3i63qiYJ00mbb9COwQWhRZqyO+4LxfkZUNPCAHka72JvU3oSxU40n4svIn4Xw7YRPFldv3v6Bl3BtgjTBiq8QBIrQzCuhHErTW6EuKWJGMFmaC7cXjiqKvUvYa/68z7cxbHb9cWmjSXDfqer4k1feJcncPt5G6RQgnxgmcEu5kPf86vUy/OROOaOXYb/RWW25zqUF9rAQ35Fwf9AgMlAPY33LCwyEEemMKFRHw4WZhnH4aYZ1CduCCs9j+V+lMHZOZY9BPw6KMMJ+b72tC5UctwW8MJ67GFIWmdAgMBAAECggEAPvfo6J2Xl6gPkp+otRQAt6dRSek2BWphsYpFLfsVgEiPEZtmoSkY860N5ELBDNTAvs2cLk+3lR1zLXb7i6Vl45lgAyzq3Y84kdBcfKVH3e4fHRQBWF6j6+p2apgxHufxZbmTIvBultrCPACVLEu1Ww8pfsM/vlrjCDf+yvrQXpcG++fKyWmJJQ3xXZYIgjWZtKJFJebBRnKySQjB26FXKq+uVYUv5Cm/DqqIFtJSs/SURSOyvN9S3imUz8cTAzALXlexrRTo39o7eQL4+DNRvtsHxRURC3E1ppvrE14aqZlqxuSHH5YWVsvyFIoSVO9bcqa97J2KbfC9iT/04hTLnQKBgQD2e3TdwPBMcH+AYbePSFY6DLkTCokbI5ecO+TRUKSo/fzZJ0hncJXp6I2sKjBnmHjaGVlCQcRu3h8zxjqpBlK/liFZKF5vnUFF33U4h+OGzCzfu5mlJsN8HoWyXJ4KJY0N2d7JOb4r5+qyDgRKIMNKLccSyeU3yv4lWqhKAm9KiwKBgQDVRW9/0Ua/gS16D6cea11ZpHI6mgjgeuTMDBhqvYx3BrhampfZZDHwL0S1Xc+NHFif3F/ur9L4UwlM2P2Kbv03MAapcSTWnZ/sJU1AKdFl72xwmkq0vQz8gSxObteyLlgiDNNmzBgziFTLUHoZeGi42ryKnwO6Vqqzm3L3l5CpdwKBgQDAZF81VIt87vbm699OzQTZLOMtdLTOZTrLLYkOxSax7gb2LY57h0rNGMO01f2Qb1gtzUl5yUId0+2BCULyekgO2Y3QPQ1xi8rOUnz6Ej/MEQUZ4iIs4hQGhwCO13JYszTl0eDvKs5BETaFoyFAB1DITvErvkHYCe/Ukm33zuy1vwKBgChxfm9ytEPkr0cSaNKv8YfqU28hfsVzCKhZMtgrEdQQhi1IW7tx8LZngFQUciOEWJoYJGkTFqLYvE7CZ3I1EffBN8IyHpZEVetmN3wPchIukRXZbIlRwICxzkEha+3yM+xhGkXINl6vX8UegckKuHE1qcNv3Dkd7kkZFXg2WcyJAoGAQaYk04NGrtAAyn+4uxW8PYhTfE5oLJBXNy+8GuKP4xxR/nf4RlWbVEIoCloN9vhF+U+56+cpx1s4mkdEv8XLWvklmrt8seP0ASg36g+6wSFoQLZfCAl/gzp2WDwvqGEW243jkg246Ra0gzBNHncSKIXOHWJzV01J9k9MGpgTbLU=}
  public-key: ${JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzVeS3Zm2+ZaYGmJBDP1COLyJo64EFY7mE6RRyFZbyJbqB1fbx5d4ut6omCdNJm2/QjsEFoUWasjvuC8X5GVDTwgB5Gu9ib1N6EsVONJ+LLyJ+F8O2ETxZXb97+gZdwbYI0wYqvEASK0MwroRxK01uhLiliRjBZmgu3F44qir1L2Gv+vM+3MWx2/XFpo0lw36nq+JNX3iXJ3D7eRukUIJ8YJnBLuZD3/Or1MvzkTjmjl2G/0Vltuc6lBfawEN+RcH/QIDJQD2N9ywsMhBHpjChUR8OFmYZx+GmGdQnbggrPY/lfpTB2TmWPQT8OijDCfm+9rQuVHLcFvDCeuxhSFpnQIDAQAB}